### ISSUE TITLE
Tests being discovered but not run

### ISSUE THREAD

**Issue by johnjmur0** [meakbiyik/vscode-r-test-adapter#16]
Hello, 

Probably a configuration problem but I haven't been able to find much Q&A on this extension online. I've just installed the extension, and it can discover my existing testthat tests properly. 

![image](https://user-images.githubusercontent.com/87945603/155885836-7c6f1813-63a1-431a-92b5-a429cca3e877.png)

One thing is that it doesn't actually discover the individual tests which would be ideal (as stated in the README 'running individual tests is now possible contrary to the file-based atomicity of testthat API'). 

I have added the path to my Rscript.exe in the settings as stated (and also as an environment variable for good measure). 

![image](https://user-images.githubusercontent.com/87945603/155885868-9fec54b2-95fa-4df0-81dc-c453875328db.png)

When I attempt to execute any of the tests, something starts (i.e. I see the play button change to red stop button), but the process stops abruptly. No tests are marked as failed, completed or skipped. I can see this output from 'R Test Adapter Log' showing the process (starts, says it finished after a few seconds, but didn't actually do anything). 

![image](https://user-images.githubusercontent.com/87945603/155885923-cefe2129-cba9-46dd-a0f7-cbf056a5a44b.png)

Regarding devtools, I have it installed in a renv (which is maybe the source of the problem), but I'm not exactly sure what constitutes the environment in this sentence from the README 'devtools to be installed for the environment Rscript is connected to.'  I'm able to execute the tests manually using devtools (utilizing radian package for R terminal within VS Code) 

![image](https://user-images.githubusercontent.com/87945603/155886079-94f2932a-9b55-46ac-8b25-6277f39e4329.png)

Thank you!
Jack

**Comment by meakbiyik** [comment]
As noted, the extension is able to detect and run individual tests normally, and the reason why nothing runs for your case is because extension cannot detect the tests - so there is nothing to run. 

Not sure about why that is the case though - I am guessing the loader can find the files, but the parser is unable to find the tests inside files - so when you press run, the tests are indeed run but no results can be reported (since there is nothing to report for).

Can you share a test file, or some example tests? This might be an issue with [r-tree-sitter](https://github.com/r-lib/tree-sitter-r) as well, I need to check what happens.

**Comment by johnjmur0** [comment]
Thank you for the quick response! 

Your suggestion about test discovery helped - I had specified the tests declarations with testthat::test_that('example_test' { ...
Removing the testthat:: invocation allowed them to be discovered. 

![image](https://user-images.githubusercontent.com/87945603/155897895-0725eda2-4a90-4921-a3e9-5c59b678b748.png)

However I'm still getting the same behavior - test run starts, and 'finishes' without any actual update. 

![image](https://user-images.githubusercontent.com/87945603/155897913-1de1dbd3-6103-4fc1-9a3f-13d11bd91a6e.png)

Below the 'basic dummy test' that I tried running that was discovered and 'finished' but not actually completed (I couldn't attach the file).

![image](https://user-images.githubusercontent.com/87945603/155898310-ede7ca36-bb65-4fd6-8c85-27b8ea9961b4.png)


Folder structure can be seen in the top of the above image (couldn't get it formatted nicely in this comment):

{Package} > tests > testthat/test_example.R, testthat.R

 testthat.R just has `library(testthat)` in it.

 Let me know if you'd prefer I push this example to a different public repo, I figured this would be just as quick to copy over! 

Thanks again, 
Jack

**Comment by meakbiyik** [comment]
First, I am very surprised that test_that:: prefix created a problem, I will solve that ASAP. 

The other issue is also slightly clearer now. I ran some tests, and the main issue I noted was that error information is lost: devtools apparently writes to stderr instead of stdout when there is an issue, but still returns with code 0, so my current implementation did not capture what it complains about. 

I have written a workaround for that, and tested with the stuff you sent. In my version, devtools complain that:

```
Error: Could not find package root. Is your working directory inside a package?
Execution halted
```

Which is quite natural, testthat requires the folder to be a healthy package. Therefore when I add DESCRIPTION and NAMESPACE to your example, everything works nicely:

```
{"type":"start_reporter"}
{"type":"start_file","filename":"test-new.R"}
{"type":"start_test","test":"dummy test"}
{"type":"add_result","context":{},"test":"dummy test","result":"failure","location":"test-new.R:2:5","filename":"test-new.R","message":"TRUE not equal to FALSE.\n1 element mismatch"}
{"type":"end_test","test":"dummy test"}
{"type":"end_file","filename":"test-new.R"}
{"type":"end_reporter"}
```

Now the thing is, this is not the case in your version, the tests run on CMD but not in the adapter. In order to determine the root cause, I am releasing a new version as soon as possible with verbose errors and fixed test detection. Try it out and let me know what devtools says, and we can finally sort this out.

**Comment by meakbiyik** [comment]
v0.5.2 is up! Try it out, and report the errors you encounter. I am guessing #12 and this issue will be the same thing, but we need to see some results. Hopefully I can then fix that next week.

**Comment by johnjmur0** [comment]
Thank you very much for the quick update! There was an improvement, but then it seemed to go back to the previous behavior :(

So I first updated the extension (v0.5.2), ran the test, and got this error  
`Error: 'test_active_file' is not an exported object from 'namespace:devtools'`

Which made me think that this statement was not true "devtools to be installed for the environment Rscript is connected to". (I still haven't been able to find any R documentation about discovering which environment RScript is connected to though). So I tried adding some library(devtools) calls in my testthat.R and tests themselves. I also tried re-installing devools, which went to my "personal" library (C:/Users/Documents/R/win-library/4.0), as the library where RScript.exe is located is not writable (C:\Program Files\R\R-4.0.5\library). I'm tentatively assuming that is the 'environment' where devtools needs to be? 

After I tried these devtools calls, the tests went back to not really being run. I tried restarting VSCode and re-installing the plugin, but continue getting the same behavior. I haven't been able to get that original error message about 'test_active_file()' to display again. 

From 'R Test Adapter Log':
![image](https://user-images.githubusercontent.com/87945603/156180208-b89cdc8c-c37a-49b2-abec-981879dcf9d3.png)

![image](https://user-images.githubusercontent.com/87945603/156180246-810674e0-8c84-4ddc-b57f-276948333a6e.png)

Thank you again for being so helpful!

**Comment by meakbiyik** [comment]
Ah, we found the issue 🙂 Your devtools is not up-to-date, test_active_file() is a new function! devtools is deprecating the function I previously used (est_file()

**Comment by meakbiyik** [comment]
Can you try again when you have time? The new version should solve most of the issues, if not all.

**Comment by johnjmur0** [comment]
Hi @meakbiyik, thank you for your patience! So generally I'm still getting the same behavior - tests are being found, test runs start, and finish without actually displaying failures. After restarting and reloading most everything, I am getting a bit more info from the output of the test adapter log - it is discovering devtools v2.4.3, the latest. This potentially disproves one of my hunches that the extension wasn't discovering devtools due to my use of a virtual environment. It also discovers the Rscript version I specified in my settings. 

![image](https://user-images.githubusercontent.com/87945603/156663334-f2b0b8b7-45a5-4652-8648-f33d3c0de041.png)

My "test_example.R" remains the dummy test of expect_equal(TRUE, FALSE)  

![image](https://user-images.githubusercontent.com/87945603/156663513-fe694fe0-3137-44f2-a8ec-7b8ed2fdfe4d.png)

Modifying the values in the testthat.R file don't seem to have any affect on the output of the test adapter log or the behavior of the tests not failing, but here it is in case. 

![image](https://user-images.githubusercontent.com/87945603/156663864-e33996b2-c679-4b5f-a168-27504350eb17.png)

While this overwhelmingly feels like a user error/configuration problem, I really appreciate you taking the time to debug this with me! Being able to execute R unit tests in VS Code same as Python has been something I've wanted to get working for a while, so thank you again!

**Comment by meakbiyik** [comment]
@johnjmur0 Thanks a lot for your interest. After seeing the reports also provided in #12, I realized that at this point it makes no sense trying to force a deprecated API to work, so I am migrating to the Native UI where I know the extension works. This will take some time though as I am also cleaning the code at the same time, and the logic seems to be a bit different. Will keep you posted.

**Comment by meakbiyik** [comment]
Until then, you can try using the Native UI by setting `testExplorer.useNativeTesting` to `True` - see #12 for an image of that.

**Comment by meakbiyik** [comment]
An update after a long time: now that this extension is using the native Testing API of VSCode, I will assume all previous issues with unknown/unreproducible errors to be stale. Please feel free to reopen if you can reproduce them clearly with the new version, v0.6.0.
