### ISSUE TITLE
Non-Standard Directory Structure Question

### ISSUE THREAD

**Issue by corey-dawson** [meakbiyik/vscode-r-test-adapter#18]
Hello,
One shortcoming of testthat is that it wants to assume a package is being developed (and not an app). In developing an app, i create a folder structure such as:
app
&nbsp;&nbsp;| -- R
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- app.R
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- tests
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- testthat.R
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- testthat
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| -- mytest.R

When running the app or tests from this repo, I would change to the working directory to /app/R and be able to run tests using the 'test_dir' command and providing the path from the current working directory

```
testthat::test_dir("tests/testthat")
```
Unfortunately, I dont have a good enough idea of how to make that integrate with vscode's testing tab. When I try to run, I get the error:
```
Error: i Loading vscodereporter
Error: Could not find package root. Is your working directory inside a package?
Execution halted
```

Any help would be appreciated

**Comment by meakbiyik** [comment]
Sorry for the late response. As this extension is using devtools to run tests (a requirement as testthat does not provide the necessary API), it assumes a proper structure:

```
app
  | -- R
      | -- app.R
      | -- tests
            | -- testthat.R
            | -- testthat
                  | -- mytest.R
 | -- DESCRIPTION
 | -- NAMESPACE
```

It is unfortunately not possible to use the extension otherwise, though I imagine you can just put placeholder files that "fakes" this structure to trick devtools into working with your package.
