### ISSUE TITLE
Testing units are shown repeatedly on Testing Panel

### ISSUE THREAD

**Issue by franzbischoff** [meakbiyik/vscode-r-test-adapter#19]
Hello!

I've seen strange behavior in the UI when we have a workspace with multiple folders.

A new tree of tests is fed on the Testing panel for every folder added to the workspace.

For example, there are 12 folders in this workspace:

<img src="https://user-images.githubusercontent.com/984592/172657691-a383ae07-742a-404e-af4a-0dcf43af5185.png" width=400px>

So, there are 12 trees in Testing Panel, each root with its 12 folders! 🤣 

<img src="https://user-images.githubusercontent.com/984592/172657813-8087c03b-70c1-447a-968d-6a48c357bebe.png" width=400px>

**Comment by meakbiyik** [comment]
I want to move to the Native adapter, and actually the base code is complete, but just do not have the time to add the tests. I will try to finish that some time soon, and afterwards you can check out again to see if this is an extension or API problem.

**Comment by meakbiyik** [comment]
An update after a long time: now that this extension is using the native Testing API of VSCode, I will assume all previous issues with unknown/unreproducible errors to be stale. Please feel free to reopen if you can reproduce them clearly with the new version, v0.6.0.

**Comment by franzbischoff** [comment]
It works, not as I expected, but this may be an issue for the VSCode devs. The unit tests are all there, not repeated, but also not divided by folder :-)
