### ISSUE TITLE
tree-sitter error on VSCode for windows

### ISSUE THREAD

**Issue by franzbischoff** [meakbiyik/vscode-r-test-adapter#2]
Hello, I see that there was an issue about tree-sitter (closed) but IDK the context.

What is happening here is only on Windows. If I use the remote connection for WSL (Linux) for example, the plugin works fine.
I also see that the plugin folder contains an executable tree-sitter that Is not .exe. I think it is installing the Linux executable instead of the windows .exe.
I could not make any workaround putting tree-sitter.exe there (I'm not an expert in this programming language).

This is the popup error that appears when I open VSCode: "Windows cannot find 'tree-sitter'. Make sure you wrote the name correctly and try again."

![image](https://user-images.githubusercontent.com/984592/108540452-1e7e5e80-72d9-11eb-961a-92c0ee7d7f66.png)

And here is the output log:

```
[2021-02-19 17:33:07.065] [INFO] Test Explorer found
[2021-02-19 17:33:07.065] [INFO] Creating adapter for d:\Workspaces\RStudio\matrixprofiler
[2021-02-19 17:33:07.066] [INFO] Initializing testthat adapter
[2021-02-19 17:33:07.066] [INFO] Initialized testthat adapter
[2021-02-19 17:33:07.066] [INFO] Registering adapter for d:\Workspaces\RStudio\matrixprofiler
[2021-02-19 17:33:07.066] [INFO] Loading testthat tests
[2021-02-19 17:33:07.066] [INFO] Initialization finished
[2021-02-19 17:33:12.976] [ERROR] Error: Command failed: start /B "c:\Users\Franz\.vscode\extensions\meakbiyik.vscode-r-test-adapter-0.2.2\node_modules\tree-sitter-cli" tree-sitter query c:\Users\Franz\.vscode\extensions\meakbiyik.vscode-r-test-adapter-0.2.2\query\detect_testthat.scm d:\Workspaces\RStudio\matrixprofiler\tests\testthat\test-windowfunc.R -c
The system cannot find the file tree-sitter.

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'start /B "c:\\Users\\Franz\\.vscode\\extensions\\meakbiyik.vscode-r-test-adapter-0.2.2\\node_modules\\tree-sitter-cli" tree-sitter query c:\\Users\\Franz\\.vscode\\extensions\\meakbiyik.vscode-r-test-adapter-0.2.2\\query\\detect_testthat.scm d:\\Workspaces\\RStudio\\matrixprofiler\\tests\\testthat\\test-windowfunc.R -c',
  stdout: '',
  stderr: 'The system cannot find the file tree-sitter.\r\n'
}
```

**Comment by meakbiyik** [comment]
@franzbischoff thanks for the detailed bug report. I am also a Windows user, so I put on some time to work around the bugs I have encountered but I haven't seen this one before. Can you check out the below stuff for me to pinpoint the exact issue:

1. The files in the directory "c:\\Users\\Franz\\.vscode\\extensions\\meakbiyik.vscode-r-test-adapter-0.2.2\\node_modules\\tree-sitter-cli", i.e. can you do an `ls -al` in there and print it out?
2. Also, can you do the same for "c:\\Users\\Franz\\.vscode\\extensions\\meakbiyik.vscode-r-test-adapter-0.2.2\\node_modules"?
3. Where did you install the extension from, the Marketplace or directly the `Extensions` tab in the VS Code? Can you reinstall it, preferably via the Extensions tab directly?

**Comment by franzbischoff** [comment]
1:
![image](https://user-images.githubusercontent.com/984592/108544103-e299c800-72dd-11eb-8f17-859336e69760.png)

2:
![image](https://user-images.githubusercontent.com/984592/108544168-fba27900-72dd-11eb-9780-7f217eb9c739.png)

3: from inside the VSCode Extensions tab, I came here in the repo and see that the version is the same so I didn't bother to install from here.

**Comment by meakbiyik** [comment]
Ah I see what's going on I think. I will take a wild guess and say that you installed the extension while you were using the VS Code via WSL, so VS Code ran `npm install` inside Linux bash and npm downloaded the Linux binaries, and at the end you can't use those binaries with the VS Code in Windows, while they run perfectly in WSL. VS Code normally handles this by explicitly reinstalling the extensions to Windows/WSL whenever necessary though, so I am still not 100% sure why this has happened (see https://code.visualstudio.com/docs/remote/wsl#_managing-extensions). 

As a test/solution to see if this was indeed the case, can you open non-WSL VS Code, go to `Extensions`, and uninstall/reinstall the extension? 

BTW, you ran the `ls` commands not in "c:\Users\Franz\.vscode\extensions\meakbiyik.vscode-r-test-adapter-0.2.2\node_modules\tree-sitter-cli", but in "~\.vscode\extensions\meakbiyik.vscode-r-test-adapter-0.2.2\node_modules\tree-sitter-cli", just in case can you run it again in the former path? The first one is in Windows while the other is in WSL. You can do

`ls -al \mnt\c\Users\Franz\.vscode\extensions\meakbiyik.vscode-r-test-adapter-0.2.2\node_modules\tree-sitter-cli`

inside WSL.

**Comment by meakbiyik** [comment]
Also, are you using WSL version 1 or 2? Version 1 could explain cross-OS issues like this.

**Comment by franzbischoff** [comment]
I'm using WSL2, but was the other way around. I first installed in a
Windows workspace. Than it failed. So I tried on WSL and it worked...

**Comment by meakbiyik** [comment]
@franzbischoff I tried to remove the cli call by using node-tree-sitter, as I have tried for multiple extensions in the past, and it again failed (at least it did not succeed in the way I want, as I do not want to keep track of the Electron version of vscode -- see https://github.com/microsoft/vscode/issues/658 if interested).

I have one last suspicion in mind, that is, for some reason `npm install` builds the tree-sitter binary as `tree-sitter` in some Windows computers (like mine) and `tree-sitter.exe` in some others. To see if that's indeed the case here, can you run 

```
ls c:\Users\Franz\.vscode\extensions\meakbiyik.vscode-r-test-adapter-0.2.2\node_modules\tree-sitter-cli
```

and send the output? The outputs you previously provided are for WSL's, and it does not show anything wrong as expected.

**Comment by meakbiyik** [comment]
Ah no... I understand it all now. It is all on me. Will fix this soon.

**Comment by meakbiyik** [comment]
@franzbischoff The last release (v0.3.0) should fix everything. Can you try and let me know if the issue is resolved? Be careful with the version though, VS Code might silently wait for a reload to update the extension.

**Comment by franzbischoff** [comment]
Solved, thank you!

--
Francisco Bischoff
