### ISSUE TITLE
Tests failing with R6 classes

### ISSUE THREAD

**Issue by jankgithub** [meakbiyik/vscode-r-test-adapter#26]
Hi,

we have found [this bug ](https://gitlab.com/zielinskipp/vs-code-bug) while using the R6 classes in vs code

Any help greatly appreciated!

**Comment by meakbiyik** [comment]
Thanks for the very detailed bug report, I will check this out. My guess is that this is a bug in R parser, so I need to check if there are any fixes on that front.

**Comment by meakbiyik** [comment]
There was a bug in my tree-sitter query, thanks a lot for finding it out. The new release should fix it, it will be up soon.

**Comment by jankgithub** [comment]
looking forward to give it a try! Thanks!

**Comment by meakbiyik** [comment]
Release 0.7.0 is now up 🚀
