### ISSUE TITLE
test hierarchy not show in GUI

### ISSUE THREAD

**Issue by yonicd** [meakbiyik/vscode-r-test-adapter#6]
in testthat there are two ways to structure tests either through `testthat::test_that` or by `testthat::describe` and then inside of describe you can use `testthat::it` for example here in this package [repository](https://github.com/yonicd/slickR/blob/master/tests/testthat/test-div.R).

The extension GUI [does not pick up](https://github.com/meakbiyik/vscode-r-test-adapter/blob/fa044bb50506a75375212d3416edce43f3ddbb10/src/testthat/parser.ts#L69) the later hierarchy and would be a nice feature to have to know the structure of tests within the files and what expectations descriptions are within each describe block. (notice that each file is expanded, but empty)

<img width="219" alt="Screen Shot 2021-03-07 at 9 30 16 AM" src="https://user-images.githubusercontent.com/1755487/110243305-be69f800-7f27-11eb-831b-6e895c026de6.png">

**Comment by meakbiyik** [comment]
I will admit, I am not very well versed with R, so I did not even know this. It will be a priority, thanks for noting.

**Comment by meakbiyik** [comment]
@yonicd DBB testing with testthat is now supported, let me know if anything does not work as intended.

**Comment by yonicd** [comment]
thanks for applying the fixes! 

i noticed two things.

 - it is doubling the test dirs in the sidebar
<img width="440" alt="Screen Shot 2021-03-22 at 7 35 24 PM" src="https://user-images.githubusercontent.com/1755487/112071204-c8a20e00-8b45-11eb-8099-1e0f8b75abbb.png">

- this also makes tests run twice if i run it from root (all tests)

- it is not reporting failed expectations, ie if i change an expectation to fail it is still reporting passing

<img width="1134" alt="Screen Shot 2021-03-22 at 7 37 03 PM" src="https://user-images.githubusercontent.com/1755487/112071373-fedf8d80-8b45-11eb-82ac-9b2aa934e309.png">

```
[2021-03-22 23:33:29.661] [INFO] Running testthat tests ["root"]
[2021-03-22 23:33:29.664] [INFO] Running testthat tests ["root"]
[2021-03-22 23:33:45.543] [INFO] Test run finished
[2021-03-22 23:33:45.551] [INFO] Test run finished
```

**Comment by meakbiyik** [comment]
I am also seeing this behavior in the screenshot of your other issue, and I am puzzled: there are two main suites (R (testthat)s) which can only happen if there are two adapters registered, and the log also indicates so. The adapter is only registered when the extension is activated, so I suspect that there is something wrong with your installation of the extension: can you check your list of extensions to see if there are any duplicates, remove `R Test Adapter` extension and reinstall?

**Comment by yonicd** [comment]
i reinstalled the extension still same issue.

```
> code --version
1.54.3
2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
x64

```

here are the installed extensions

```
> code --list-extensions --show-versions
bierner.docs-view@0.0.9
DavidAnson.vscode-markdownlint@0.39.0
dpastoor.vscode-nm@0.2.0
eamodio.gitlens@11.3.0
GitHub.vscode-pull-request-github@0.24.0
hbenl.vscode-test-explorer@2.19.6 <-----
Ikuyadeu.r@1.6.5
Ikuyadeu.r-pack@0.0.2
ivan-bocharov.stan-vscode@0.2.2
James-Yu.latex-workshop@8.16.1
johnpapa.vscode-peacock@3.9.1
karigari.chat@0.35.0
meakbiyik.vscode-r-test-adapter@0.4.0 <-----
ms-azuretools.vscode-docker@1.11.0
ms-python.python@2021.3.658691958
ms-toolsai.jupyter@2021.3.619093157
ms-vscode-remote.remote-containers@0.163.2
ms-vscode-remote.remote-ssh@0.65.1
ms-vscode-remote.remote-ssh-edit@0.65.1
ms-vsliveshare.vsliveshare@1.0.4018
ms-vsliveshare.vsliveshare-audio@0.1.91
ms-vsliveshare.vsliveshare-pack@0.4.0
natqe.reload@0.0.6
pkosta2005.heroku-command@0.0.8
RDebugger.r-debugger@0.4.6
REditorSupport.r-lsp@0.1.14
shd101wyy.markdown-preview-enhanced@0.5.17
skyapps.fish-vscode@0.2.1
streetsidesoftware.code-spell-checker@1.10.2
tht13.html-preview-vscode@0.2.5
torn4dom4n.latex-support@3.6.0
yzhang.markdown-all-in-one@3.4.0
```

**Comment by meakbiyik** [comment]
Then the only possibility here that I can see is your workspace is somehow duplicated. See https://github.com/hbenl/vscode-test-adapter-api/blob/master/README.md#registering-your-test-adapter-with-the-test-explorer, if there are two workspaces in vscode.workspace.workspaceFolders that points to the same directory, then I imagine this could've happened. Though, with very high probability this is a bug on the main extension, maybe something similar to https://github.com/hbenl/vscode-test-explorer/issues/74. I would advise to close the workspace cleanly and reopen and see if this persists, or if you can find any error that connects the issue directly to my extension I would be happy to help.

The only fishy thing here is reporting passed for failed expectations. Does this happen also when you run the tests per file or individually, or is it only when you run them via "run all tests"?

**Comment by yonicd** [comment]
Ok. All ways that i run test don’t show failing (single, folder, all)

**Comment by yonicd** [comment]
yes. multiroot workspace caused the duplication problem. is there a way around it? or do i need to only work with a single root if i use the extension?

**Comment by meakbiyik** [comment]
Multiroot itself should not cause any problems, but if both roots include the same package then there is simply no way out: the adapter does not know that there are other adapters also watching the same package, each adapter is isolated. In your last example there seems to be three adapters active at the same time, one is trying to run the test with a temporary file, and the others detect the temporary file and reload the tests. 

I may resolve that by manually registering only one adapter (it seems this is possible), but then, which workspace folder will be the root? This is an impossible decision and would cause a feature regression, so it is just not possible to resolve from my side.

The question that is crucial here (and the reason why I am keeping this issue open since I can resolve it) is why are tests not failing. Do they still behave this way when you use a single root/workspace?

**Comment by yonicd** [comment]
>Multiroot itself should not cause any problems, but if both roots include the same package then there is simply no way out: the adapter does not know that there are other adapters also watching the same package, each adapter is isolated. In your last example there seems to be three adapters active at the same time, one is trying to run the test with a temporary file, and the others detect the temporary file and reload the tests.

this isnt my usecase though. i have the folder only in one of the roots, when i do have multiroot workspaces.

**Comment by meakbiyik** [comment]
I am closing this issue as it went stale.
