### ISSUE TITLE
Run test at cursor position with keyboard shortcut

### ISSUE THREAD

**Issue by tschoesi** [meakbiyik/vscode-r-test-adapter#8]
Is there a way to run the test the cursor is currently positioned at/in? Having a keyboard shortcut for this would be very helpful and time saving!

**Comment by meakbiyik** [comment]
Indeed there is, though from the main extension: 

`
test-explorer.run-test-at-cursor: Run the test at the current cursor position
`

For more info, you can check the "Commands" section of this [link](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer)

**Comment by tschoesi** [comment]
Awesome, thank you! :)
